
services:

  core:
    build:
      context: ./src
    container_name: learning-langchain
    env_file:
      - .env
    ports:
      # - ${PORT:-1865}:80
      - 5678:5678 # debugger port
    extra_hosts:
      - "host.docker.internal:host-gateway" # This add an entry to /etc/hosts file in the container mapping host.docker.internal to the host machine IP addr, allowing the container to access services running on the host, not only on Win and Mac but also Linux. See https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host and https://docs.docker.com/reference/cli/docker/container/run/#add-host
    environment:
      # Timezone
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - ./src:/app
    restart: unless-stopped
    tty: true
    stdin_open: true
